# Generated by Django 5.0.6 on 2026-05-16 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('META', 'Meta / Facebook / Instagram'), ('GOOGLE', 'Google Ads')], max_length=20)),
                ('account_id', models.CharField(max_length=120)),
                ('account_name', models.CharField(blank=True, max_length=180)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'account_name'],
                'unique_together': {('owner', 'provider', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='AdCampaignLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(default='OUTCOME_TRAFFIC', max_length=80)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destination_url', models.URLField()),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('creative', models.JSONField(blank=True, default=dict)),
                ('platform_campaign_id', models.CharField(blank=True, max_length=120)),
                ('platform_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('dry_run', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_launches', to='campaigns.campaign')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='integrations.adplatformconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
